<?php
/**
 *
 */
?>
<section class="register">
 <h2>Register</h2>
 <?php if ( $this->error): ?>
 <p class="error">
   Please correct the form.
 </p>
 <?php endif;?>

 <?php
 $form = $this->form;
 $form->prepare();
 $form->setAttribute('action',$this->url(NULL,array('controller' =>'UsersController', 'action' => 'process')));
 $form->setAttribute('method', 'post');
 echo $this->form()->openTag($form);
 ?>

<dl class='znd_form'>
<dt><?php echo $this->formLabel($form->get('name'));?>
<dd><?php
   echo $this->formElement($form->get('name'));
   echo $this->formElementErrors($form->get('name'));
?></dd>
</dt>
<dt><?php echo $this->formLabel($form->get('mail'));?>
<dd><?php
   echo $this->formElement($form->get('mail'));
   echo $this->formElementErrors($form->get('mail'));
?></dd>
</dt>
<dt><?php echo $this->formLabel($form->get('pass'));?>
<dd><?php
   echo $this->formElement($form->get('pass'));
   echo $this->formElementErrors($form->get('pass'));
?></dd>
</dt>
<dt><?php echo $this->formLabel($form->get('confirm_password'));?>
<dd><?php
   echo $this->formElement($form->get('confirm_password'));
   echo $this->formElementErrors($form->get('confirm_password'));
?></dd>
</dt>
<dd><?php
   echo $this->formElement($form->get('submit'));
   echo $this->formElementErrors($form->get('submit'));
?></dd>
</dl>

 <?php echo $this->form()->closeTag($form); ?>
</section>