<?php
/**
 * User Login form
 */
?>
<section class="register">
 <h2>Login</h2>
 <?php if ( $this->error): ?>
 <p class="error">
   Please correct the form.
 </p>
 <?php endif;?>

 <?php
 $form = $this->form;
 $form->prepare();
 $form->setAttribute('action',$this->url('user/postlogin',array('controller' =>'UsersController', 'action' => 'postlogin')));
 $form->setAttribute('method', 'post');
 echo $this->form()->openTag($form);
 ?>


<dl class='znd_form'>

<dt><?php echo $this->formLabel($form->get('email'));?>
<dd><?php
   echo $this->formElement($form->get('email'));
   echo $this->formElementErrors($form->get('email'));
?></dd>
<dt><?php echo $this->formLabel($form->get('password'));?>
<dd><?php
   echo $this->formElement($form->get('password'));
   echo $this->formElementErrors($form->get('password'));
?></dd>
<dd><?php
   echo $this->formElement($form->get('submit'));
   echo $this->formElementErrors($form->get('submit'));
?></dd>
</dl>

  <?php echo $this->form()->closeTag($form); ?>
</section>

<?php echo $this->translate('Not registered?'); ?>
	<a href="<?php echo $this->url('user/register',array('action' => 'register')) . ($this->redirect ? '?redirect='.$this->escapeUrl($this->redirect) : '') ?>">
<?php echo $this->translate('Sign up!'); ?></a>

